blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexListView.as_view(), name= 'index'),
    path('post/<slug:slug>/', views.PostDatailView.as_view(), name= 'post'),
    path('page/<slug:slug>', views.PageDatailView.as_view(), name= 'page'),
    path('created_by/<int:id>/', views.CreatedByListView.as_view(), name= 'created_by'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name= 'category'),
    path('tag/<slug:slug>/', views.TagListView.as_view(), name= 'tag'),
    path('search/', views.SearchListView.as_view(), name= 'search'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls') ),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from typing import Iterable
from utils import images
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Tag(models.Model):

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(
        max_length = 255
    )
    slug = models.SlugField(
        unique = True, blank = False, max_length = 255
    )

    def __str__(self) -> str:
        return self.name
    


class Category(models.Model):

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(
        max_length = 255
    )
    slug = models.SlugField(
        unique = True, blank = False, max_length = 255
    )

    def __str__(self) -> str:
        return self.name
    

class Page(models.Model):

    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"

    title = models.CharField(max_length = 55)
    slug = models.SlugField(
        unique = True, blank = False, max_length = 255
    )

    is_public = models.BooleanField(default = False)

    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_public:
            return reverse('blog:index')
        return reverse('blog:page', args=(self.slug,))


class Post(models.Model):

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    title = models.CharField(max_length = 55)
    slug = models.SlugField(
        unique = True, blank = False, max_length = 255
    )

    is_public = models.BooleanField(default = False)

    content = models.TextField()
    excerpt = models.CharField(max_length = 255)

    cover = models.ImageField(upload_to='img/%Y/%m', blank=True, null=True, default=None)
    cover_public = models.BooleanField(default = False)

    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='post_created_by',
    )
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)
    update_by = models.ForeignKey(User , on_delete = models.SET_NULL, default = None, blank = True, null = True, related_name = "post_update_by" )

    category = models.ForeignKey("Category", on_delete=models.SET_NULL, default = None, null = True, blank = True)
    tag = models.ManyToManyField(Tag, blank = True)

    def __str__(self):
        return self.title
    
    def save(self,*args, **kwargs):

        cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False


        
        if self.cover:
            cover_changed = cover_name != self.cover.name

        if cover_changed:
            self.cover = images.resize_images(self.cover, 900, True, 80)

        return super_save
    
    def get_absolute_url(self):
        if not self.is_public:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))
    

site_setup/models.py
from django.db import models
from utils import validator

# Create your models here.

class MenuLink(models.Model):

    class Meta:
        verbose_name = "Menu Link"
        verbose_name_plural = "Menu Links"

    text = models.CharField(max_length = 50)
    url_or_file = models.CharField(max_length = 2048)
    new_tab = models.BooleanField(default = False)
    site_setup = models.ForeignKey('SiteSetup', on_delete = models.CASCADE, null = True, blank = True, default = None)

    def __str__(self) -> str:
        return self.text
    

class SiteSetup(models.Model):
    class Meta:
        verbose_name =  "Setup"
        verbose_name_plural = "Setup"

    title = models.CharField(max_length = 65)
    description = models.CharField(max_length = 255)

    show_header = models.BooleanField(default = True)
    show_menu = models.BooleanField(default = True)
    show_search = models.BooleanField(default = True)
    show_pagination = models.BooleanField(default = True)
    show_description = models.BooleanField(default = True)
    show_footer = models.BooleanField(default = True)

    favicon = models.ImageField(upload_to='assets/favicon/%Y/%m/', blank=True, default='', validators=[validator.validate_png])

    def __str__(self) -> str:
        return self.title

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from blog import models
from django.db.models import Q
from django.http import Http404, HttpRequest, HttpResponse
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User


# Create your views here.


class IndexListView(ListView):
    template_name = 'blog/pages/index.html'
    context_object_name = 'page_obj'
    paginate_by = 9
    queryset = models.Post.objects.filter(is_public = True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = f'Home - '
        return context
    
class PostDatailView(DetailView):
    model = models.Post
    template_name = 'blog/pages/post.html'
    slug_field = 'slug'
    context_object_name = 'post'

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset().filter(is_public = True)

        return qs
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if self.context_object_name == None:
            raise Http404()
        
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f'{self.object.title} - Post - '
        return context

class PageDatailView(DetailView):
    model = models.Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset().filter(is_public = True)

        return qs
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if self.context_object_name == None:
            raise Http404()
        
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f'{self.object.title} - Page - '
        return context

class CreatedByListView(IndexListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._temp_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username

        page_title = user_full_name + ' - ' + ' Autor - '

        context.update({
            'page_title': page_title,
        })

        return context
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context['user'].pk)
        return qs
    
    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('id')
        user = User.objects.filter(pk=id).first()

        if user is None:
            raise Http404()

        self._temp_context.update({
            'id': id,
            'user': user,
        })

        return super().get(request, *args, **kwargs)
    
class CategoryListView(IndexListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._temp_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_name = self.object_list[0].category.name

        page_title = str(category_name) + ' - ' + ' Categoria - '

        context.update({
            'page_title': page_title,
        })

        return context
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(category__slug = self._temp_context['slug'])
        return qs
    
    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        category = models.Category.objects.filter(slug = slug)

        if slug is None:
            raise Http404()

        self._temp_context.update({
            'slug': slug,
            'category': category,
        })

        return super().get(request, *args, **kwargs)
    

class TagListView(IndexListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._temp_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_name = self.object_list[0].tag.first().name

        page_title = str(tag_name) + ' - ' + ' Tag - '

        context.update({
            'page_title': page_title,
        })

        return context
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(tag__slug = self._temp_context['slug'])
        return qs
    
    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        tag = models.Tag.objects.filter(slug = slug)

        if slug is None:
            raise Http404()

        self._temp_context.update({
            'slug': slug,
            'tag': tag,
        })

        return super().get(request, *args, **kwargs)




class SearchListView(IndexListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._search_value = ''

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self._search_value = request.GET.get('search', '')
        return super().setup(request, *args, **kwargs)
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(Q(title__icontains=self._search_value) | Q(excerpt__icontains=self._search_value) | Q(content__icontains=self._search_value))
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_title = self._search_value[:30] + ' - ' + ' Search - '

        context.update({
            'page_title': page_title,
        })

        return context
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if self._search_value == '':
            return redirect('blog:index')
        return super().get(request, *args, **kwargs)

blog/templates/blog/partial/_card_post.html
<article class="card">

    {% if post.cover %}
        {% if post.cover_public %}
            <div class="card-cover-wrapper ">
                <a class="cover-link" href="{% url "blog:post" post.slug %}">
                    <img class="card-cover" src="{{post.cover.url}}" alt="post.title" loading="lazy">
                </a>
            </div>
        {% else %}
            <DIV class="cover-spacing"></DIV>
        {% endif %}

    {% else %}
        <DIV class="cover-spacing"></DIV>
    {% endif %}

    <div class="card-text-wrapper">
        <div class="card-title-wrapper">
            <a class="card-title-link" href="{% url "blog:post" post.slug %}">
                <h2 class="card-title">{{post.title}}</h2>
            </a>
        </div>

        <div class="card-content-wrapper">
            <div class="card-content">
                <p>{{post.excerpt}}</p>
            </div>
        </div>
    </div>

    <div class="card-actions">
        <a class="card-action-link" href="{% url 'blog:post' post.slug %}">
            <span>Read</span>
            <i class="fa-solid fa-circle-arrow-right"></i>
        </a>
    </div>

</article>

blog/templates/blog/partial/_footer.html
<footer class="footer">
    <div class="footer-content">
        <p>{{setup.title}}</p>
    </div>
</footer>

blog/templates/blog/partial/_head.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if setup.favicon %}
        <link rel="shortcut icon" href="{{ setup.favicon.url}}" type="image/png">
    {% endif %}
    <link rel="stylesheet" href=" {% static "blog/css/remedy/remedy.css" %}">
    <link rel="stylesheet" href=" {% static "blog/css/style.css" %}">
    <title>{{page_title}}{{setup.title}}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

blog/templates/blog/partial/_header.html
<header class="width-wide section-gap">
    <div class="section-content">
        <div class="heading center">
            <h1><a href="{% url "blog:index" %}">{{setup.title}}</a></h1>
        </div>

        <div class="description center">
            <p class="description-content">{{setup.description}}</p>
        </div>

        <div class="search center">
            <form class="search-form" action="{% url "blog:search" %}" method="get" >
                <div class="search-content">
                    <input
                    class="search-input" 
                    type="text"
                    id="search"
                    name = "search"
                    placeholder="Search">

                    <button type="submit" class="search-btn">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </form>
        </div>

        <nav class="menu">
            <ul class="menu-list">

                {% for link in setup.menulink_set.all %}
                    {% if link.new_tab %}
                        <li class="menu-item">
                            <a href="{{link.url_or_file}}" target="_blank">{{link.text}}</a>
                        </li>
                    {% else %}
                        <li class="menu-item">
                            <a href="{{link.url_or_file}}">{{link.text}}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
        
    </div>
</header>

blog/templates/blog/partial/_pagination.html
            {% if page_obj and page_obj.has_other_pages %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a class="forward-left" href="?page=1"><i class="rotate fa-solid fa-forward-fast"></i></a>
                        <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-circle-left"></i></a>
                    {% endif %}
            
                    <span class="current">
                        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-circle-right"></i></a>
                        <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa-solid fa-forward-fast"></i></a>
                    {% endif %}
                </span>
            </div>
            {% endif %}